export const TABLES = {
  USERS: 'users',
  EMAIL_VERIFICATION_CODES: 'email_verification_codes',
  PROFILES: 'profiles',
  PROFILE_FOLLOWERS: 'profile_followers',
  SOCIAL_MEDIA: 'social_media',
  COMMUNITIES: 'communities',
  COMMUNITY_FOLLOWERS: 'community_followers',
  TAGS: 'tags',
  RECIPE_TAGS: 'recipe_tags',
  RECIPES: 'recipes',
  RECIPE_STEPS: 'recipe_steps',
  INGREDIENTS: 'ingredients',
  RECIPE_INGREDIENTS: 'recipe_ingredients',
  PERSONAL_COLLECTIONS: 'personal_collections',
  PERSONAL_COLLECTIONS_RECIPES: 'personal_collections_recipes',
};
