export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 20;

export const PASSWORD_HASH_ROUNDS = 10;

export const VERIFICATION_CODE_LENGTH = 128;

export const NICKNAME_MIN_LENGTH = 3;
export const NICKNAME_MAX_LENGTH = 32;

export const AUTH_VALIDATION_ERRORS = {
  NICKNAME_EMPTY: 'auth.nickname_empty',
  NICKNAME_INVALID: 'auth.nickname_invalid',
  NICKNAME_MIN_LENGTH_INVALID: 'auth.nickname_min_length_invalid',
  NICKNAME_MAX_LENGTH_INVALID: 'auth.nickname_max_length_invalid',

  EMAIL_EMPTY: 'auth.email_empty',
  EMAIL_INVALID: 'auth.email_invalid',

  PASSWORD_EMPTY: 'auth.password_empty',
  PASSWORD_INVALID: 'auth.password_invalid',
  PASSWORD_MIN_LENGTH_INVALID: 'auth.password_min_length_invalid',
  PASSWORD_MAX_LENGTH_INVALID: 'auth.password_max_length_invalid',
};

export const AUTH_ERRORS = {
  EMAIL_ALREADY_TAKEN: 'auth.email_already_taken',
  NICKNAME_ALREADY_TAKEN: 'auth.nickname_already_taken',
  VERIFICATION_CODE_NOT_FOUND: 'auth.verification_code_not_found',
  INVALID_EMAIL_OR_PASSWORD: 'auth.invalid_email_or_password',

  INVALID_ACCESS_TOKEN: 'auth.invalid_access_token',
  INVALID_REFRESH_TOKEN: 'auth.invalid_refresh_token',
};

export const AUTH_SUCCESS_MESSAGES = {
  ACCOUNT_CREATED: 'auth.account_created',
};

/*
export const AUTH_VALIDATION_ERRORS = {
  NICKNAME_EMPTY: 'AUTH.NICKNAME.EMPTY',
  NICKNAME_INVALID: 'AUTH.NICKNAME.INVALID',
  NICKNAME_MIN_LENGTH_INVALID: 'AUTH.NICKNAME.MIN',
  NICKNAME_MAX_LENGTH_INVALID: 'AUTH.NICKNAME.MAX',

  EMAIL_EMPTY: 'AUTH.EMAIL.EMPTY',
  EMAIL_INVALID: 'AUTH.EMAIL.INVALID',

  PASSWORD_EMPTY: 'AUTH.PASSWORD.EMPTY',
  PASSWORD_INVALID: 'AUTH.PASSWORD.INVALID',
  PASSWORD_MIN_LENGTH_INVALID: 'AUTH.PASSWORD.MIN',
  PASSWORD_MAX_LENGTH_INVALID: 'AUTH.PASSWORD.MAX',
};

export const AUTH_ERRORS = {
  EMAIL_ALREADY_TAKEN: 'AUTH.EMAIL.ALREADY_TAKEN',
  NICKNAME_ALREADY_TAKEN: 'AUTH.NICKNAME.ALREADY_TAKEN',
  VERIFICATION_CODE_NOT_FOUND: 'AUTH.GENERAL.VERIFICATION_CODE_NOT_FOUND',
  INVALID_EMAIL_OR_PASSWORD: 'AUTH.GENERAL.INVALID_EMAIL_OR_PASSWORD',

  INVALID_ACCESS_TOKEN: 'AUTH.INVALID_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN: 'AUTH.INVALID_REFRESH_TOKEN',
};

export const AUTH_SUCCESS_MESSAGES = {
  ACCOUNT_CREATED: 'AUTH.ACCOUNT_CREATED',
};
*/
